services:
    nginx-rtmps:
        build: .
        volumes:
            - ./.ssl:/ssl
        ports:
            - 1935:1935
            - 1936:1936
            - 8080:8080
            - 443:443 # TODO
        environment:
            - SSL_DOMAIN=mydomain.com
